### ISSUE TITLE
Don't remove function names during initialization

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wizer#1]
Wizer currently removes the names for all functions when initializing a `.wasm` module. Is it possible to change, either generally or optionally with a parameter?

**Comment by fitzgen** [comment]
Are you seeing the `name` custom section removed completely? We should copy all custom sections over.

I think maybe there might be an off-by-one because we remove the initialization function, which may make engines throw out the whole `name` custom section. I'll look into it a little more.

**Comment by fitzgen** [comment]
Hm wait, no, we don't remove the `wizer.initialize` function, we just un-export it. Therefore there shouldn't be any off-by-ones in the name section.

**Comment by fitzgen** [comment]
Hm okay I can reproduce with the `rust_regex` test.

**Comment by fitzgen** [comment]
Fix over in https://github.com/bytecodealliance/wasm-tools/pull/190; once that merges, I'll cut a release and then update the dep here.
