### ISSUE TITLE
Feature request/question: Ability to mark some code to not be pre-initialised

### ISSUE THREAD

**Issue by JakeChampion** [bytecodealliance/wizer#30]
Howdy 👋 

Is there a way to mark some code to not be pre-initialised? For example, any code which is in the optimization path but is trying to make host calls?

I came across an [issue with using Fastly's js-compute-runtime](https://github.com/fastly/js-compute-runtime/issues/3#issuecomment-894836830) which stems from some code being optimized by Wizer that ideally shouldn't be.

I can work around the issue by changing parts of my program's code to no longer be optimisable by Wizer
but I do wonder if this will be a common enough scenario that perhaps Wizer could be instructed to not pre-initialise some code paths.

**Comment by tschneidereit** [comment]
I think this might not be possible—at least I can't think of a way to do it.

However, what I think should be happening is that we trap whenever content tries to call a hostcall that's not actually available—which is what's happening here. @fitzgen I thought that's what we're doing, but apparently not?

@JakeChampion to be clear, trapping on these hostcalls wouldn't fix anything—it'd just fail earlier :) I'll comment on the js-compute-runtime issue on how to fix the issues you're running into with that.

**Comment by fitzgen** [comment]
Yeah there isn't really a good way for Wizer to determine which state should be snapshotted and which shouldn't. The best thing to do is to write your program such that it only makes changes you want to be snapshotted in the `wizer.initialize` function.

**Comment by tschneidereit** [comment]
@JakeChampion the next release of js-compute-runtime will [address this](https://github.com/fastly/js-compute-runtime/pull/20) by throwing on attempts to use request-handler-only functionality.

Given that this isn't really something that can be improved further in Wizer, I'll go ahead and close this issue.
