### ISSUE TITLE
Called import is ignored

### ISSUE THREAD

**Issue by kripken** [bytecodealliance/wizer#39]
The readme says

> The initialization function may not call any imported functions. Doing so will trigger a trap and wizer will exit.

However I seem to be seeing different behavior. Testcase:

```wat
(module
  (import "a" "b" (func $import))
  (global $global (mut i32) (i32.const 0))
  (func $foo (export "wizer.initialize")
    (global.set $global (i32.const 10))
    (call $import)
    (global.set $global (i32.const 20))
  )
)
```
```wat
$ wizer a.wasm -o b.wasm
$ echo $?
0
$ wasm-dis b.wasm
(module
 (type $none_=>_none (func))
 (import "a" "b" (func $fimport$0))
 (global $global$0 (mut i32) (i32.const 20))
 (func $0
  (global.set $global$0
   (i32.const 10)
  )
  (call $fimport$0)
  (global.set $global$0
   (i32.const 20)
  )
 )
)
```
Wizer removed the export and updated the global to 20 so it seems to have just skipped over the call to the import?

**Comment by fitzgen** [comment]
Thanks for the bug report! Fix is over in https://github.com/bytecodealliance/wizer/pull/40
