### ISSUE TITLE
Compilation error on nightly Rust with crates.io version

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wizer#51]
A user filed [this issue](https://github.com/bytecodealliance/rustix/issues/354), about a compilation failure when building wizer from crates.io with nightly Rust, which is due to the version of wizer on crates.io using an old version of cap-std. It looks like this is fixed in https://github.com/bytecodealliance/wizer/pull/47; would it be possible to release a new version of wizer to crates.io?

**Comment by fitzgen** [comment]
Published 1.4.0!
