### ISSUE TITLE
Can't open files with WASI SDK >12 in certain runtimes?

### ISSUE THREAD

**Issue by guregu** [bytecodealliance/wizer#59]
Hello, not sure if this overlaps with #24. Apologies if it does, feel free to close.

It seems that for WASI SDK with versions higher than 12, adding Wizer breaks preopening directories, but only for Wasmer? WASI SDK 12 works fine.

Is this just a matter of Wasmer being behind on the spec? If it's purely a Wasmer issue, I'll make an issue there instead. wasmtime and wasmedge seem to be totally fine. Any hints towards figuring this out would be appreciated.

Here is a sample program to demonstrate this (C):
```c
#include <stdio.h>
#include <sys/stat.h>
#include "wizer.h"

WIZER_DEFAULT_INIT();

int main(int ac, char *av[]) {
	struct stat st = {0};
	int ret = stat(av[1], &st);
	printf("ret %d size %lld\n", ret, st.st_size);
	return 0;
}
```

```bash
$ cat test.txt
hello world
$ stat test.txt
  File: test.txt
  Size: 12              Blocks: 8          IO Block: 4096   regular file
Device: 810h/2064d      Inode: 1293537     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  guregu)   Gid: ( 1000/  guregu)
Access: 2022-09-18 19:46:26.155241300 +0900
Modify: 2022-09-18 16:49:19.175241300 +0900
Change: 2022-09-18 16:49:19.175241300 +0900
 Birth: -

# compiling
$ $WASI_CC -Isrc/wizer test.c
$ wizer --allow-wasi --dir . -o test.wasm a.out

# with WASI SDK 15:
$ wasmtime --dir . test.wasm -- test.txt
ret 0 size 12
$ wasmedge --dir . test.wasm test.txt
ret 0 size 12
$ wasmer --dir . test.wasm -- test.txt
ret -1 size 0

# with WASI SDK 12:
$ wasmtime --dir . test.wasm -- test.txt
ret 0 size 12
$ wasmedge --dir . test.wasm test.txt
ret 0 size 12
$ wasmer --dir . test.wasm -- test.txt
ret 0 size 12
```

Sorry if this is unrelated, feel free to close and I'll ask the Wasmer folks instead.

**Comment by fitzgen** [comment]
> Sorry if this is unrelated, feel free to close and I'll ask the Wasmer folks instead.

Yeah I would suggest doing that. Good luck!
