### ISSUE TITLE
Question: Why does Wizer work? (sicerely)

### ISSUE THREAD

**Issue by benmkw** [bytecodealliance/wizer#60]
If a rust/c/c++ programm ist compiled to wasm using llvm and wizer can preexecute some code, isn't each of these cases a bug in llvms constant folding? (Similarly for wasm-opt and llvm dead code elimination)

Is there a set of samples which show how wizer can perform certain "optimisations" which are inherently impossible for llvm (I'm not talking about `--allow-wasi` which is obviously not possible for llvm to do).

If there are certain samples, would arm-wizer or x86-wizer be possible/ does it already exist? Meaning: Would preexecution also work/ be benefitial for non wasm targets or is this something which is specific to wasm where maybe llvm just is not able to output "optimal" wasm but its possible to output "optimal" x86?

Thanks

**Comment by fitzgen** [comment]
In principal it is mostly possible, and there are compilers (cheerp) and wasm post-processors (binaryen) that will do this for C++ global constructors as much as they can (not sure why they can do better than LLVM in this particular case, but that's a question for those projects).

However, there are a few things that make it so this doesn't always happen in practice, or even would be impossible for the compiler:

* As you mention, with WASI enabled and/or using custom linkers to allow custom imports during initialization time, the compiler can't see through all of the initialization function and the initialization function might even do things like read files from disk and load them into memory. Compilers generally avoid non-determinism at build time like file IO and definitely don't have access at all to the custom linker imports.
* There is no toolchain convention that the initialization function is run before any other export is called, and the compiler certainly doesn't assume that, so it won't optimize with that assumption in mind. This may change somewhat with the component model.
* In general, constant prop/folding in compilers isn't complete and will stop/give up at certain operations; particularly common is bailing out when reaching something that is side effectful like `memory.grow`. Not totally sure if LLVM does that, but Wizer has no such constraints.

I don't have, and haven't investigated and compiled, any sort of complete list of examples where LLVM gives up and Wizer can take over.

> If there are certain samples, would arm-wizer or x86-wizer be possible/ does it already exist? Meaning: Would preexecution also work/ be benefitial for non wasm targets or is this something which is specific to wasm where maybe llvm just is not able to output "optimal" wasm but its possible to output "optimal" x86?

These sorts of tools have definitely been built in the past. [`glibc` used to provide an `unexec` function that Emacs used to create an executable from an initialized process's memory.](https://lwn.net/Articles/673724/)

Something that makes this kind of thing easier for Wasm than an OS process is the well-defined and relatively small set of stateful resources: just memories, globals, and tables and that's it. Makes it easier to get correct, fewer moving parts, etc.

I also think mobile OSes do this kind of thing as well, but I'm not super familiar with that space so I could be wrong.

------------

Anyways, I hope this answers your question. Going to close this issue, but feel free to ask follow ups / clarifications / etc.

**Comment by benmkw** [comment]
Thanks for the response! Wizer is definitely a really cool project given its achievements and I'm also looking forward to using it at some point!

The reference to unexec is also verry interesting, still makes me curious whats the current state of these things.
Given something like
```cpp
int foo(int i) {
  auto interpreter = get_interpreter(#embed file.lua);
  return  interpreter.bar(i);
}
```

should in theory be able to run the interpreter up to the point where i is used but I think the main hurdle at the moment, as you said, is memory allocation which is not visible to the optimiser.

> I also think mobile OSes do this kind of thing as well, but I'm not super familiar with that space so I could be wrong.

I also vaguely remember android apps getting larger in version 3/4 or whatever because they are somewhat more prepared to launch, but I'm unable to find a reference quickly.

**Comment by benmkw** [comment]
I opened the following topic in the llvm forum https://discourse.llvm.org/t/preexecution/65953
